### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by revolt666** [stefanceriu/SCXcodeSwitchExpander#8]
It simply doesn't work, and never did for me. I used Xcode 5 and now I'm using Xcode 6

**Comment by fredrikbonander** [comment]
You car didn't start, not even with Xcode 6 ? If you revert to Xcode 4 does your coffee machine work then?

It's not really clear what you mean. Be specific, how and why doesn't it work. There's now way of knowing what the problem is if the  description is "MAMA, It simply doesn't work". Error messages, steps to reproduce, environment, anything. 

Please read this: http://stackoverflow.com/help/how-to-ask

Consider how the code would look like if the repo owner only spent as much time on the code as you did on this ticket.

**Comment by revolt666** [comment]
I'm sorry, I didn't mean to insult someone or something.

I know how to ask, but I formulated this on purpose because it in fact explains all the problem.

Firstly, the __plugin__ doesn't work, and that's obvious, since the ticket is posted here.

And by _"doesn't work"_ I meant that it does nothing, hence, doesn't work.

So, I'm writing `swi`, then hit <kbd>enter</kbd>, then _Xcode_ autocompletes the switch for me, then I'm writing my enum's variable name inside the parentheses, but no `case` keyword appears.

Also, it was kinda of a start of conversation, knowing that some follow up questions will arrive. I'm sorry again if it's not ok to do this, but I didn't know what details will the owner need from me.

**Comment by stefanceriu** [comment]
Hey,

That's not much to go on but please make sure that you're on the latest version and that the values you are trying to switch through are defined through NS_ENUM or NS_OPTIONS (from the readme: "only works with NS_ENUM but keeps default Xcode behaviour for old style enums")

**Comment by revolt666** [comment]
Thanks for the help, I read the _README_ but didn't pay attention to the actual code. I thought the new Xcode autocompletes `enum` with `NS_ENUM` but it looks like it doesn't. Thank you for this awesome plugin.

**Comment by stefanceriu** [comment]
You're welcome :)
